### ISSUE TITLE
Instructor Field will break team.md generation

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/2014-04-14-pycon-ngs#2]
@ctb your name at this is write as "Titus Brown" but at all others that you teach is used, "C. Titus Brown". Could you (or I) fix it to "C. Titus Brown"?

**Comment by wking** [comment]
On Sun, Jul 13, 2014 at 12:38:53PM -0700, r-gaia-cs wrote:

> @ctb your name at this is write as "Titus Brown" but at all others
> that you teach is used, "C. Titus Brown". Could you (or I) fix it to
> "C. Titus Brown"?

I approve of this “fix the source” approach, but I expect sooner or
later we'll hit this problem and not be able to contact the author of
the inconsistent repository.  It might be easier to have
.mailmap-style name-canonicalization for those cases.  That would also
allow swcarpentry/site maintainers to store temporary workarounds
while they wait for feedback from authors who will eventually respond.

**Comment by ctb** [comment]
feel free to fix!
